id: P040BF068
initial_creation_type: input
source_metadata:
  Title: Le Mahavastu
  Editor: Par E. Senart
  Publisher: A L'imprimerie Nationale
  Place of Publication: Paris, France
  Year: '1890'
  Mahāvastu Avadāna (Vol 2):
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: '2020'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:26:06.419427'
last_modified_at: '2022-03-08T17:26:06.419442'
